# --- Main Application Settings ---
[main]
# The Instagram username of the public profile you want to scrape.
target_profile = "betches"

# The maximum number of post URLs to collect from the profile page.
# Recommended: Start with a small number (e.g., 10-50) to test.
num_posts = 5

# If true, the browser will run in the background without a visible window.
# Recommended: true for performance, false for debugging.
headless = false

# The minimum and maximum random delay (in seconds) between batches of requests.
# This helps avoid rate-limiting. Recommended: 2-5 seconds.
rate_limit_seconds_min = 2
rate_limit_seconds_max = 4

# General-purpose retry count for various operations.
max_retries = 3

# Number of posts to open in new tabs and scrape in a single batch.
# A smaller number (e.g., 3-5) uses less memory and is safer.
batch_size = 4

# If true, the batch size will be randomized slightly to appear more human.
randomize_batch = true

# Number of retries when scrolling the main profile page if no new content loads.
page_scroll_retries = 3

# Duration (in seconds) for the simulated human mouse movement in each new tab.
human_mouse_move_duration = 0.5

# Save scraped data to the final file after every N posts.
# A smaller number is safer against crashes but increases disk I/O.
save_every = 2

# Number of retries when scrolling for comments if no new content loads.
comments_scroll_retries = 1

# Number of scroll steps to perform when collecting comments on a post.
# Higher values will collect more comments but take longer. Recommended: 30-60.
comment_scroll_steps = 5

# --- Data and File Path Settings ---
[data]
# The main directory where all output files will be stored.
output_dir = "outputs"

# These paths use placeholders like {target_profile} which will be automatically filled.
posts_path = "outputs/{target_profile}/posts_{target_profile}.txt"
metadata_path = "outputs/{target_profile}/metadata_{target_profile}.jsonl"
skipped_path = "outputs/{target_profile}/skipped_{target_profile}.txt"
tmp_path = "outputs/{target_profile}/scrape_results_tmp_{target_profile}.jsonl"

# IMPORTANT: Update this with the name of the cookie file generated by `login_Save_cookie.py`.
cookie_file = "src/igscraper/cookies.pkl"

# --- Logging Settings ---
[logging]
# The logging level.
# Recommended: "INFO" for normal runs, "DEBUG" for troubleshooting.
level = "DEBUG"

