# --- Main Application Settings ---
[main]
# --- CHOOSE ONE MODE ---

# MODE 1: Scrape from profiles.
# A list of Instagram profiles to scrape. Each has a 'name' and 'num_posts'.
target_profiles = [
    { name = "textsfromyourex", num_posts = 3 },
    { name = "ladbible", num_posts = 1 }
 ]

# run_name_for_url_file = "my_url_file_scrape" # Used for output folder name in URL file mode

# These paths use placeholders like {target_profile} which will be automatically filled.
# In URL file mode, {target_profile} is replaced by `run_name_for_url_file`.
# urls_filepath = "urls_to_scrape.txt"

# If true, the browser will run in the background without a visible window.
# Recommended: true for performance, false for debugging.
headless = false

# The minimum and maximum random delay (in seconds) between batches of requests.
# This helps avoid rate-limiting. Recommended: 2-5 seconds.
rate_limit_seconds_min = 2
rate_limit_seconds_max = 4

# General-purpose retry count for various operations.
max_retries = 3

# Number of posts to open in new tabs and scrape in a single batch.
# A smaller number (e.g., 3-5) uses less memory and is safer.
batch_size = 4

# If true, the batch size will be randomized slightly to appear more human.
randomize_batch = true

# Number of retries when scrolling the main profile page if no new content loads.
page_scroll_retries = 3

# Duration (in seconds) for the simulated human mouse movement in each new tab.
human_mouse_move_duration = 0.5

# Save scraped data to the final file after every N posts.
# A smaller number is safer against crashes but increases disk I/O.
save_every = 2

# Number of retries when scrolling for comments if no new content loads.
comments_scroll_retries = 1

# Number of scroll steps to perform when collecting comments on a post.
# Higher values will collect more comments but take longer. Recommended: 30-60.
comment_scroll_steps = 3

# --- Data and File Path Settings ---
[data]
# The main directory where all output files will be stored.
output_dir = "outputs"



posts_path = "outputs/{target_profile}/posts_{target_profile}.txt"
metadata_path = "outputs/{target_profile}/metadata_{target_profile}.jsonl"
skipped_path = "outputs/{target_profile}/skipped_{target_profile}.txt"
tmp_path = "outputs/{target_profile}/scrape_results_tmp_{target_profile}.jsonl"

# IMPORTANT: Update this with the name of the cookie file generated by `login_Save_cookie.py`.
cookie_file = "src/igscraper/cookies_1758028035.025856.pkl"

# --- Logging Settings ---
[logging]
# The logging level.
# Recommended: "INFO" for normal runs, "DEBUG" for troubleshooting.
level = "DEBUG"
log_dir = "outputs/logs"
